### ISSUE TITLE
Upgrade to Nominatim 3.1

### ISSUE THREAD

**Issue by tonytw1** [tonytw1/nominatim-ac#11]
Confirm compatibility with the latest Nominatim release.

**Comment by tonytw1** [comment]
Small change to the get place function method signature; nothing huge.

**Comment by PraveenAlexis** [comment]
Can we update to niminatim 3.7

**Comment by tonytw1** [comment]
I've tested with Nominatim 3.7 and the export queries seem to be compatible.
I've updated the README to confirm that it's compatible with a 3.7 schema.

https://github.com/tonytw1/nominatim-ac/issues/19
